image: ubuntu:bionic

stages:
    - test

integration_tests:
    stage: test
    before_script:
        - apt-get update -qq
        - apt-get install -y -qq shunit2 make rsyslog
        - service rsyslog start
    script:
        - make test
