image: ubuntu:bionic

stages:
    - test

integration_tests:
    stage: test
    before_script:
        - apt-get update -qq
        - apt-get install -y -qq shunit2 make rsyslog
        - service rsyslog start
        - mkdir -p /var/tmp/
        - chmod 777 -R /var/tmp/
    script:
        - make test
